### ISSUE TITLE
Paragon app was off-line and and would not connect

### ISSUE THREAD

**Issue by chrisnaber** [FirstBuild/FirstBuild-Mobile#22] opened 2015-07-13 12:45 UTC
I setup my mobile app on Friday and it was working fine.  When I came back after the weekend, it showed as 'off line' on my phone and would not connect.  
I closed the app and reopened and it still showed as off line.
I asked Taylor to try it on his phone and he had the same issue.  
I 'deleted' the paragon profile in the app and tried to recreate it but it still did not connect.
I power cycled the acm and them it worked correctly. 
I asked Taylor to try it on his phone and it worked correctly.

**Comment by jeffddrake** [comment] 2015-07-15 14:53
I'm still digging into this but I can re-create this during testing. So far it seems like it is connected to when the probe goes offline or online again. For some reason, and not all of the time, when that state changes it stops advertising for a phone to connect and never starts again until you power cycle.

**Comment by jeffddrake** [comment] 2015-07-17 15:03
I have patched a couple of places where the device could potentially not be connected to a mobile device but not advertising. So far it's been successful but i'm not closing this issue yet until more testing is done since I didn't have an absolute root cause.

**Closed** 2015-08-13 18:49 UTC
